### ISSUE TITLE
Set number of mem write in setstate function of test_cpu.c

### ISSUE THREAD

**Issue by pwiegele** [koenk/gbit#1]
Hi,

took me a while to find out that I have to set the variable `num_mem_accesses `here https://github.com/koenk/gbit/blob/master/test_cpu.c#L39.

Otherwise the number of memory writes is not tracked correctly.
I think it makes sense to add this to the boilder plate code.

Thanks for writing this testframework!

**Comment by koenk** [comment]
You're right this should be part of the boiler plate. Thanks!
